### PR TITLE
Style edits for mobile

### PR DESCRIPTION
**Pull request by Vivalldi**
Good to go.
Report anything that looks wrong or any bugs.

### CODE REVIEW

**Comment by flaviocopes** [comment]
Tested, looks perfect! :) 

I got this minor issue on the PHP Info page
screen shot 2015-09-05 at 11 32 42

Ah on this same page, I got a JS error that prevents sidebar to appear. Will look into this on monday if you don't address them before that

**Comment by Vivalldi** [comment]
I know the fix for the issues that you mentioned. I should have it done by this evening (EST). Gotta get home to recompile the scss on my Mac. You know any good practices to edit a pull request to show my changes?

**Comment by flaviocopes** [comment]
You can just push to the pull request branch, and it updates automatically :)

**Comment by Vivalldi** [comment]
Mended. Feel free to take another look into it.

**Comment by Vivalldi** [comment]
@flaviocopes do you need me to fix the conflicts or are you good?

**Comment by flaviocopes** [comment]
@Vivalldi can you merge develop into this branch, so it is up to date?

**Comment by Vivalldi** [comment]
@flaviocopes. Merged.

**Comment by rhukster** [comment]
Ok i've merged this in to develop!  Any further bug fixes can be done as PR's on develop.  Thanks so much for you help @Vivalldi !!!

**Comment by Vivalldi** [comment]
Anytime. Thank you.

**Comment by flaviocopes** [comment]
:+1: :+1:

**Pull request merged**
