### PR TITLE
Only display the translated logout message

### PR DESCRIPTION
**Pull request by tyrion273**

### CODE REVIEW

**Comment by flaviocopes** [comment]
:+1:

**Comment by tyrion273** [comment]
Are you OK with it? Because at first it worked but somehow the message is not displayed at all.

**Comment by tyrion273** [comment]
I think something is buggy because after inserting the line again the message is displayed again but only in English although my backend language is German.

**Comment by flaviocopes** [comment]
No issues for me with latest develop branches of grav+admin

**Pull request merged**
