### PR TITLE
Implementation of the setting to enable secure deletion of pages

### PR DESCRIPTION
**Pull request by lauroguedes**
To avoid accidental deletion, I implemented a secure deletion system in which the user has to type the word DELETE into a text field for the confirm deletion button to be enabled. By default this plugin setting is disabled.

demo-secure-delete

### CODE REVIEW

**Comment by rhukster** [comment]
This is pretty cool!  Good idea

**Comment by lauroguedes** [comment]
Yes, I got the idea after I accidentally lost some data, as the button was the same color as cancel and there was no turning back this was a solution that solved

**Comment by lauroguedes** [comment]
Another thing that could be done is to have a specific permission to create, edit and delete pages in admin, so that would create another layer of security.

**Comment by mahagr** [comment]
There are already separate permissions for different page actions built into the upcoming Flex pages. :)

**Pull request merged**
