### PR TITLE
User manager

### PR DESCRIPTION
**Pull request by beneva52**
User manager

### CODE REVIEW

**Comment by Vivalldi** [comment]
@beneva52 there is a lot more than an update to languages.yaml going on here. It would help rhukster a ton if you could explain what all you did (and more importantly what it does).

**Comment by beneva52** [comment]
Sorry, but I have just started with GitHub and I am a bit lost with all the concept of branches, patches, pull requests and so on. I am a quick learner though.
In fact, what I have done is adding a user manager tool to the admin.

**Comment by Vivalldi** [comment]
Neat! I'll pull it into my own local site and test it. I do not have write access so I  just test and find bugs. I'll let you know if I find anything wrong that needs to be fixed.

**Comment by Vivalldi** [comment]
Could you fix your style by creating the style in the scss file? https://github.com/getgrav/grav-plugin-admin/pull/202/files#diff-7c61bf5e99ae65ecd3b67bc5a945347aR3 and then use `scss.sh` in the themes/grav/ to compile the css?

**Comment by beneva52** [comment]
Just done it, for the first time!

**Comment by rhukster** [comment]
We really had intended to have the full user manager as part of the pro version.  This was one reason why we pulled the list view in the first place.  I'm afraid that if we add this back, there will be less of a reason to pay for the pro version.  

I appreciate your contribution here, but I will have to evaluate what we can do to ensure the free version remains feature-rich, and the pro version is still a compelling purchase option.

If we can't convince people to buy the pro version, it will impact the development of Grav going forward.

**Comment by rhukster** [comment]
BTW does this PR supersede "Patch 3" ???

**Comment by beneva52** [comment]
I understand your concern, but as I noticed there was no user manager, I just wrote it...
I don't really know how I made "Patch 3" and couldn't find a way to delete that branch.

**Comment by rhukster** [comment]
Closing this as we have made solid progress for our own usermanager in our Pro version of the plugin.  If you wish to create this as a standalone plugin fro the free admin, that is totally doable.

**Comment by beneva52** [comment]
No problem, I will wait for the Pro version anyway.
When will it be available ('soon' is not an answer :)) ?

**Pull request closed without merging**
