### PR TITLE
Added Japanese Language.

### PR DESCRIPTION
**Pull request by Unrealno1**
I add all the Japanese translations.
There will be funny, Because I don't understand all the features.

### CODE REVIEW

**Comment by flaviocopes** [comment]
Thanks @Unrealno1! Can you also add the latest string I just added to the lang file (FULLY_UPDATED) and make sure the commit does not delete that string in the other languages? :)

**Comment by flaviocopes** [comment]
(sorry, while we're at it: 4 strings left at the end of the file:

    METADATA_KEY: "Key (e.g. 'Keywords')"
    METADATA_VALUE: "Value (e.g. 'Blog, Grav')"
    USERNAME_HELP: Username should be between 3 and 16 characters, including lowercase letters, numbers, underscores, and hyphens. Uppercase letters, spaces, and special characters are not allowed
    FULLY_UPDATED: Fully Updated

**Comment by Unrealno1** [comment]
Sure!

But, I do unfamiliar with English and GitHub.
I'm sorry if you wrong

**Comment by flaviocopes** [comment]
No problem ;) you can open a new PR with the old changes plus the 4 missing strings, if it comes easier to you

**Comment by Unrealno1** [comment]
Is this a good?
Thanks in Advance!

**Comment by Unrealno1** [comment]
Sorry!
change CONTENT.

**Comment by flaviocopes** [comment]
Thanks @Unrealno1, I merged the PR in 17b96ef, will get in the next admin plugin update. There are 2 missing strings (`FULLY_UPDATED` and    `SAVE_LOCATION`) at the end, you can post a new PR for that :+1:

**Pull request closed without merging**
