### PR TITLE
Feature/mobile

### PR DESCRIPTION
**Pull request by Vivalldi**

### CODE REVIEW

**Comment by Vivalldi** [comment]
sorry, wrong button press

**Comment by Vivalldi** [comment]
Should be good to go.

**Comment by nicolasdanelon** [comment]
Can I help with this? What's the difference between this PL and #91 ?

**Comment by Vivalldi** [comment]
@nicolasdanelon this one is updated more. I also left this one open by accident. I had a webhook reopen that I've taken down.

**Comment by Vivalldi** [comment]
@nicolasdanelon https://github.com/Vivalldi/grav-plugin-admin/tree/feature/mobile

**Pull request closed without merging**
