### PR TITLE
Feature custom page options

### PR DESCRIPTION
**Pull request by david-szabo97**
Related issue: https://github.com/getgrav/grav-plugin-admin/issues/1066

To avoid using JS, I added a custom value handling to 'folder' field: `@slugify-field`
If you want to automatically slugify the title and use it as your folder, just put `default: @slugify-title` to the folder field.

Possible values for `add_modals`:

- **label** - Text to be shown in the button
- **show_in** (default: bar) (values: bar|dropdown) - Determines whether to show the button in the **bar** or **dropdown**
- **blueprint** - Form blueprint to pass to modal template
- **template** - Template to use for modal (default: partials/blueprints-new.html.twig)
- **with** - Extra data for template
- **link_classes** - This will be added to the link's (button in bar) class attribute
- **modal_classes** - This will be added to the modal's class attribute

## Example
This example adds an "Add Post" button which only accepts one value, the title. Automatically puts it into the `/posts`. (You can find more examples and explanation in the https://github.com/getgrav/grav-plugin-admin/issues/1066)

**user/blueprints/admin/pages/new_post.yaml**
```yaml
form:
  validation: loose
  fields:
    section:
        type: section
        title: Add Post

    title:
      type: text
      label: Post Title
      validate:
        required: true

    folder:
      type: hidden
      default: '@slugify-title'

    route:
      type: hidden
      default: /posts

    name:
      type: hidden
      default: 'post'

    visible:
      type: hidden
      default: ''

    blueprint:
      type: blueprint
```

**user/config/plugins/admin.yaml**
```yaml
add_modals:
  post:
    label: Add Post
    blueprint: admin/pages/new_post
    show_in: dropdown
```

### CODE REVIEW

**Comment by flaviocopes** [comment]
Cool! 

Two considerations: 

1. can we use something else instead of cocur/slugify? Seems to add 3800+ files, which is a bit too many for such a simple thing as converting to a slug? Maybe add our own slugify functionality in https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Utils.php 

2. can you move the modal key in the modal itself, so it can be defined in a list in the Admin plugin blueprint? This way modals can be configured via the Admin panel.

We can then also make it possible for plugins to add new ones dynamically, with an event.

**Comment by david-szabo97** [comment]
@flaviocopes 
To be honest I totally removed the key stuff. I think we can freely rely on the index. What do you think?

**Comment by david-szabo97** [comment]
@flaviocopes Is there anything else I should do before this gets merged? Thank you.

**Comment by flaviocopes** [comment]
I tested and it looks good! Can you move the PR desc to a Cookbook entry? So people know how to use this in their sites or also plugins https://learn.getgrav.org/cookbook

**Comment by mahagr** [comment]
Umm, honestly I'm not really liking the change as it only applies to admin plugin and is hardcoded to the controller like that. I guess it's only a save thing, but still...

**Comment by flaviocopes** [comment]
I like offering plugins, or also themes, the option to add custom page creation modals, as it's easier for clients.

What in particular you don't like @mahagr, the concept of some part of the code that's implementing this?

**Comment by mahagr** [comment]
As I said, the `@slugify-title` only works from the admin when saving the data. Generally these processors are used inside of the `BlueprintForm` class to run a function call on `BlueprintForm::init()` call.

**Pull request merged**
