### PR TITLE
If user not logged in redirect to base path

### PR DESCRIPTION
**Pull request by osrecio**
Solved problem when  user not logged in can go to admin/something and view admin dashboard with Error 404.

### CODE REVIEW

**Comment by rhukster** [comment]
I'm not able to reproduce the error this is fixing.. If i try to go to `admin/dashboard` and i'm not logged in, I et redirected to the admin login.  I'm running latest develop branch though.

**Comment by osrecio** [comment]
If you try to go `/admin/anything` you will get a 404 [Image with 'error'](https://www.dropbox.com/s/gwhyths1194e7gb/screenshot_grav.png?dl=0)

**Comment by MADmarek** [comment]
rhukster, this will be part of the short report, so you can reproduce this error.

**Comment by diazwatson** [comment]
Same problem here:
page_not_found___diazwatson

This pull request fix the issue :)

**Comment by flaviocopes** [comment]
Confirmed issue and merged.

**Pull request merged**
