### PR TITLE
Re #394 update slug, route and raw route with appended number when doing a copy of the page

### PR DESCRIPTION
**Pull request by flaviocopes**
Does not change the page title, just the page route property if set in
the header, to avoid two pages with the same slug / route / raw route.

### CODE REVIEW

**Comment by flaviocopes** [comment]
Work in progress. Works at the basic level, still need to test with multilanguage and edge cases.

**Comment by flaviocopes** [comment]
Should now also solve https://github.com/getgrav/grav-plugin-admin/issues/429

**Comment by rhukster** [comment]
I think there's a minor issue.

I created a new page with folder `new-page`, and set a custom slug to `yah-baby`.  Then i copied the page.  

The resulting page was created in a folder called `yah-baby-3` and the slug was set to `yah-baby-2`.  Expected results would be `new-page-2`.

**Comment by flaviocopes** [comment]
Replicated

**Comment by flaviocopes** [comment]
Updated with fix. Covers my tests up to now.

**Pull request merged**
