### PR TITLE
Updated fontawesome and added CSS to style the Save button when creating pages

### PR DESCRIPTION
**Pull request by deviodigital**
I updated the CSS for fontawesome 4.5.0 and also added css to make the Save button in the dashboard brighter, so it stands out a little more next to the Back button.

### CODE REVIEW

**Comment by rhukster** [comment]
I'll gladly merge in the fontawesome update.

However, making changes to the save button needs to be a separate PR, also you need to provide the scss change as well as the compiled css file or it will get lost on the next compile.

**Comment by deviodigital** [comment]
Cool. I need to look over everything a little more for the css too, since that css change alters a few other buttons. I'll need to narrow down the save button. Will pr that later.

**Comment by rhukster** [comment]
Make it quick and i can sqeeze at least the Font Awesome update into the next update.. going out soon!

**Comment by rhukster** [comment]
Actually i just did it manually so closing this :)

**Comment by deviodigital** [comment]
:+1:

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-admin/commit/743ab35c1c1b90260e9b1ee43acdecaced1d4e40

**Pull request closed without merging**
