### PR TITLE
fixes #412

### LINKED ISSUE #412: User can't change his profile with certain ACL
Hi,

I've tried tu use ACL for a particular user who's simply going to add pages and edit them.
I gave this user certain permissions like this:
```
admin:
    login: true
    pages: true
```

It turns out, this user can't change his profile info, permission denied...
I'm guessing this is not the expected behaviour ?

### PR DESCRIPTION
**Pull request by Vivalldi**
Just saw this pop up in my stream and seemed like it should be easy enough...
Let me know if there are any issues

### CODE REVIEW

**Comment by flaviocopes** [comment]
`users.md` is actually also used in the User Manager in Admin Pro, that's why it has those permissions, need to find another way to fix this. Maybe have a single `user.md` page for own profile.

**Comment by flaviocopes** [comment]
Otherwise all users with access to the Admin would now see the user manager.

**Comment by Vivalldi** [comment]
Ohhh that makes sense. Forgot about the pro features.

**Comment by flaviocopes** [comment]
Closing this now, but marked on my list

**Pull request closed without merging**
