### PR TITLE
Make all existing information available on page creation

### PR DESCRIPTION
**Pull request by THoenig**
This is a possible solution for  #1172.

### CODE REVIEW

**Comment by rhukster** [comment]
This looks pretty good to me at first glance. I need to test it a bit though before merging.

**Comment by rhukster** [comment]
Ok i'm seeing an issue with this PR when creating a new page using the + button:

2017-07-25 at 7 09 pm

These values are being set by the page create modal, but really they should not be set in the frontmatter at all, they are set as properties on the page, which in turn are used to set the values, but only title should be actually stored in the frontmatter.  This is why we had that mechanism to create a simple header with only title (and possibly 'visible')

**Comment by THoenig** [comment]
I think i found a simple solution that keeps the default process untouched but adds the ability to handle additional fields.

@rhukster Could you please take a look?

**Comment by rhukster** [comment]
Yup, that works for me :)  👍

**Comment by justinhartman** [comment]
@THoenig or @rhukster can one of you tell me how I pass frontmatter options to the `'data' => $data` object so that it is saved in the frontmatter on page creation as per [this screenshot](https://github.com/getgrav/grav-plugin-admin/pull/1175#issuecomment-317918081)? I've created an Admin blueprint for `new_post.yml` as per the Grav Cookbook documentation but, as expected, when my page is getting created via the `+ Add New Post` button in the bar I only have the `title`, `date` and `author` frontmatter set. I want to pass a new frontmatter for `hidemenu: true` but I can't get that passed to the frontmatter on page creation.

In my `new_post.yml` I added this:

```yaml
data:
    hidemenu:
        type:    hidden
        default: 'true'
```

I assumed that if I used a `data:` array that is would trigger `'data' => $data` and pass the `hidemenu: true` to the frontmatter on page creation but it's not.

I know I'm missing something really basic but after about 5 hours of trying different things, I simply can't get this to work.

Any assistance would be fantastic.

**Pull request merged**
