### PR TITLE
Feature/new folder modal

### PR DESCRIPTION
**Pull request by flaviocopes**
Refs https://github.com/getgrav/grav-plugin-admin/issues/393

### CODE REVIEW

**Comment by rhukster** [comment]
new folder throws an error for me.

**Comment by flaviocopes** [comment]
Do you remember which error @rhukster? I am not able to replicate errors on root-domain Grav or when the site is in a subfolder.

**Comment by flaviocopes** [comment]
Ok problem replicated

**Comment by flaviocopes** [comment]
Will wait for the JS/modals rework to merge this

**Pull request merged**
