### PR TITLE
Fixed selecitze field not properly updating its value when the `options` attribute is provided and more than one option is selected.

### PR DESCRIPTION
**Pull request by parcand**
See #1229

### CODE REVIEW

**Comment by rhukster** [comment]
I'm not really able to get this to work, even with your last field definition:

```
  someselect:
      type: selectize
      label: Preface
      selectize:
        items:
          - ABC
          - DEF
        options:
          - text: ABC
            value: ABC
          - text: DEF
            value: DEF
          - text: GHI
            value: GHI
      validate:
        type: commalist
```

Is this what you have? What's the purpose of the `selectize: items:` ? No matter what i put i don't get any values saved.

**Comment by parcand** [comment]
Oh, I'm sorry, I can see where the confusion comes from.

I am no longer providing the `selectize: items:` as part of the field definition. This pull request introduces a small change which now automatically populate the`selectize: items:` from the actual field value.

Just to give you a bit of background information, it appears that using the `selectize: options:` attribute leads to a small glitch which prevents the widget from properly loading the comma-separated values from the HTML input element  itself. For some reason it only loads a single item, even if you previously saved more that one.

So in order to fix that problem you need to pass pre-selected values directly to the widget using the`selectize: items:`. It would be quite impractical to do it at the blueprint level, that's why I came up with this solution which merge values directly in the twig template of the selectize widget.

```yaml
    someselectize:
      type: selectize
      label: A selectize field
      selectize:
        options:
          - text: ABC
            value: ABC
          - text: DEF
            value: DEF
          - text: GHI
            value: GHI
      validate:
        type: commalist
```

**Comment by parcand** [comment]
I've done some tests with an up-to-date Grav installation and it seems to work as expected, for both config blueprints and pages blueprints (with the `header` field name prefix).

**Comment by gvstavnev** [comment]
is there a way to pass data with `@data-options` to `selectize: options:` attribute?

**Pull request merged**
