### PR TITLE
Re enable  "unset" button and fix for multiple drop zones

### PR DESCRIPTION
**Pull request by rotanadan**
"unset" on images in dropzones was shut off. I turned it back on and fixed the big issue it had when being used on pages with multiple dropzones.
"unset" will clear the image, but not delete the file from the server. This is requested a lot from clients because I often blueprint things like hero images, backgrounds, etc that are used on multiple pages.

### CODE REVIEW

**Comment by w00fz** [comment]
I am confused by this pull request because Unset is not removed as functionality at all.

You have 2 action icons you can pick from, 1 is the ⓧ unset and the other is the 🗑delete. Unset only appears as you drop a new image in the dropzone. Before saving, if you change your mind and want to remove it, you click unset and it removes it from the session. 
Once you save the page, the field with the image is persistently stored and you cannot unset it anymore, now you can only delete it, which is why the unset icon is gone.

unset_vs_delete

(note that when unset is available, also delete is but they perform the same 'unset' action)

This behavior is working fine for me so unless I am misunderstanding the issue, I can't approve this PR.

**Comment by mmorkt** [comment]
It’s easy to recreate the bug he’s fixing. Try placing the dropzone in a list and make some rows. Upload some files into the dropzones and save. Use “unset” on a file and save. Now your page is broken. As mentioned by multiple users https://github.com/getgrav/grav-plugin-admin/issues/1427

**Comment by hdwebpros** [comment]
Please re-open this PR.

@w00fz you might not be understanding what unset is truly for.

I'll give you a practical example.

Let's say you have two pages with the same hero image on each page. Then, you're asked to change one of the images. Can you see where this is going? With the current setup, you can only delete -- which deletes the file from the server. That would delete the image from **_both_** pages. 

We have multiple clients, and ourselves that run into the situation where someone wants to remove an image from a page but *not* delete it from the server. _That_ is where unset comes in. It's not just for when you first place it in a dropzone. It's for removing an image/file/whatever from a page without deleting it from the server.

It's a major issue that we have a few upset clients about. Judging from some of the interactions on Github, we aren't the only ones who see this is a big issue.

This PR addresses the main issue. It should be re-opened and tested.

**Comment by w00fz** [comment]
Also fixes #1675

**Comment by w00fz** [comment]
Thanks for clarifying @mmorkt and @hdwebpros  , it wasn't clear this was about the same image on multiple file fields! Makes sense now and PR is ok.
I cleaned up some merge conflicts and it is now merged.

Cheers all!

**Pull request merged**
