### PR TITLE
Improved class assignment for form fields in the plugin's default template

### PR DESCRIPTION
**Pull request by pmoreno-rodriguez**
See the following [Issue](https://github.com/getgrav/grav-plugin-admin/issues/2398) to more information.

### CODE REVIEW

**Review by rhukster — COMMENTED** [review]
Thanks for this PR, unforunately I can't merge it as it stands because the `es.yaml` language strings will get lost the next time I do an update from our language management tool: Crowdin.

Can you please add your language strings here also:

https://crowdin.com/editor/grav-admin/2/en-es?view=comfortable&filter=basic&value=0

Thanks!

**Comment by pmoreno-rodriguez** [comment]
@rhukster
OK. I was making some improvements to Spanish translations in Crowdin, but I didn't add the ones in this PR. I'll do it as you tell me and I hope it's okay.

Sometimes I get a little lost with my GitHub commits.

**Comment by pmoreno-rodriguez** [comment]
Hi @rhukster. I just finished the missing translations on Crowdin of the grav-admin plugin and they should now match the PR. Please tell me if everything is okay now.

**Comment by rhukster** [comment]
Thanks!

**Pull request merged**
