### PR TITLE
RTL Support for admin plugin

### PR DESCRIPTION
**Pull request by qasedak**
I've added some RTL styles and Fonts for Arabic, Persian and Hebrew languages. I'll check RTL styles and improve them by time.
Grav admin RTL
TnX.

### CODE REVIEW

**Comment by rhukster** [comment]
@qasedak do you mind updating your PR with latest changes in admin plugin so i can test with latest?

**Comment by mahagr** [comment]
If someone can update this one to be par with Grav 1.7, we could consider this addition. But as it is, we cannot merge this.

**Comment by qasedak** [comment]
I'll give it a try 😉

**Comment by mahagr** [comment]
@qasedak Thank you!

**Comment by qasedak** [comment]
I've decided to make a fresh fork and also a new Pull request from it as this one is too old...
you find it here:
https://github.com/qasedak/grav-plugin-admin/tree/rtl-support

**Comment by mahagr** [comment]
Btw, you can use `language_codes.rtl(code)`...

**Comment by mahagr** [comment]
I'm also wondering, should RTL be activated when the current language in the page is set to RTL language. You can get the current language by `grav.language.language ?? 'en'`, so you could use `language_codes.rtl(grav.language.language ?? 'en')`.

**Comment by qasedak** [comment]
yes sure! thank you. I thought it's the user's language that will be displayed so if user switches to a RTL language  we should add the RTL.css style...
but why `grav.language.getActive`  doesn't work? as [documented here](https://learn.getgrav.org/17/content/multi-language#language-logic-in-twig-templates)

**Comment by qasedak** [comment]
> 
> 
> I'm also wondering, should RTL be activated when the current language in the page is set to RTL language. You can get the current language by `grav.language.language ?? 'en'`, so you could use `language_codes.rtl(grav.language.language ?? 'en')`.

@mahagr 
as I've checked the user's preferred language overrides the first supported language (admin config section) in Admin panel i used the code below: 
`{% if language_codes.rtl(grav.user.language) %}
    {% do assets.addCss(theme_url~'/css/rtl.css') %}
{% endif %}`

**Comment by mahagr** [comment]
Ok, that will work. I guess it works fine in admin.

**Pull request closed without merging**
