### PR TITLE
90% Mobile Functionality

### PR DESCRIPTION
**Pull request by Vivalldi**
Currently the buttons on top of each page are missing (such as cache clear) due to a problem with sorting. Will be worked out in near future. Mobile site 
Please report any problems found.
Signed-off-by: vivalldi <tdce8@ahs-mesa-32002.schls.albco>

### CODE REVIEW

**Comment by rhukster** [comment]
Can we close this one?

**Comment by nicolasdanelon** [comment]
whats needs to be done? can I help?

**Comment by rhukster** [comment]
There is another newer one that I think is more accurate.  This was the original one I think.  @Vivalldi needs to confirm :)

**Comment by Vivalldi** [comment]
Yeah. i'll close it. Didn't intend to leave it open

**Pull request closed without merging**
