### PR TITLE
Some mobile fixes

### PR DESCRIPTION
**Pull request by Vivalldi**
Added a custom media for devices smaller than 335px (such as iPhone 4) as the main body in page editing was not visible

### CODE REVIEW

**Comment by rhukster** [comment]
I think this PR is obsolete with my recent changes?

**Comment by Vivalldi** [comment]
No, it's an addition to your changes.

**Comment by rhukster** [comment]
Roger I'll check it out tomorrow.

**Comment by rhukster** [comment]
Can you fix the PR so it merges?

**Comment by rhukster** [comment]
Manually fixed.

**Pull request closed without merging**
