### PR TITLE
Update languages.yaml

### PR DESCRIPTION
**Pull request by kevinkub**
Added german Translation.

### CODE REVIEW

**Comment by flaviocopes** [comment]
Thanks @kevinkub! We're refactoring the admin translations in a separate branch, the number of strings to translate has grown quite a bit (see https://github.com/getgrav/grav-plugin-admin/blob/feature/translate-admin/languages.yaml)

At the moment only italian is complete (beside english, of course). 
Still not everything is translated, so the strings are expected to grow in the next few days.

Hope to merge that branch as soon as I can, I'll merge your PR there so it's a start. Then if you want you can add some more strings :+1:

**Comment by kevinkub** [comment]
Thank you for the information. Does it make sense to fork the current branch and translate it or should I wait for you to merge with master/develop?

**Comment by flaviocopes** [comment]
I think we'll merge it into develop today, if you want you can already start translating the strings you find here: https://github.com/getgrav/grav-plugin-admin/blob/feature/translate-admin/languages.yaml#L3-L221. I'm just going through all the files and adding translations strings instead of hardcoded strings, adding new strings at the end of that file.

**Comment by flaviocopes** [comment]
@kevinkub just pushed the updated language file https://github.com/getgrav/grav-plugin-admin/blob/feature/translate-admin/languages.yaml#L3-L416. Going to finish adding the italian strings tomorrow too

**Comment by kevinkub** [comment]
I am already halfway done with the translation of a quite recent version. I hope to check in later this evening.

**Pull request closed without merging**
