### PR TITLE
Added sublabel, label classes and icon help to list field

### PR DESCRIPTION
**Pull request by pmoreno-rodriguez**
With this modification, list field labels can have a description (with markdown support), a sublabel, or a help icon, or all of them. 
Field classes are also added

### CODE REVIEW

**Comment by pmoreno-rodriguez** [comment]
Sorry. The commit https://github.com/getgrav/grav-plugin-admin/pull/2384/commits/f96499ea290c64890738f7da2dd8f570805887f7 has some issues. I'll try to fix it as soon as possible.

**Comment by rhukster** [comment]
Looks good, will need to test it before merging.

**Comment by rhukster** [comment]
Looks good, will need to test it before merging.

**Comment by rhukster** [comment]
nice, merged.

**Pull request merged**
