### PR TITLE
Update hr.yaml

### PR DESCRIPTION
**Pull request by diomed**

### CODE REVIEW

**Comment by MATsxm** [comment]
I guess you should now better use Crowdin?
https://crowdin.com/project/grav-admin

**Comment by diomed** [comment]
yup. thanks for letting me know. didn't yet know that exists. :)

**Comment by MATsxm** [comment]
It's quite new :smirk:

**Comment by flaviocopes** [comment]
Yes please put the translation on Crowdin for the Admin plugin for now. @rhukster we'll use the Crowdin translations for Admin from now on? If so, I'd close this.

**Comment by diomed** [comment]
merge this, so I don't have to do same thing twice, and in future I'll submit translations through Crowdin.

**Comment by MATsxm** [comment]
I guess this would cause Sync conflict issues, at least it's the way it is with Transifex (not sure with Crowdin)

**Comment by flaviocopes** [comment]
Yes please also add them there, since when we'll merge the translations upon doing a release, they will overwrite the translations currently stored in the repository

**Pull request closed without merging**
