### PR TITLE
Improvement: Add preview button on pages list

### PR DESCRIPTION
**Pull request by clemdesign**
Hello,

I propose this improvement in order to add a "preview" button next to "delete" button on the pages list.
A click on "preview" button will open a new page where admin user can view the page like visitor, for exemple to adjust content before publishing or know what is the article related to the page (when you have a lot of similar pages)

I think that is interesting to see the final view of article for the admin user before publishing.

Thank you,
clem.

Note: Please regenerate "template.css" with your tools because my result seems to be not the same that yours.

### CODE REVIEW

**Comment by jimblue** [comment]
Hey @clemdesign ! Can you resolve the conflict to move this PR forward please! Thank you 😄

**Comment by clemdesign** [comment]
Hey @jimblue , I resolved conflict by manual merge :sweat: but I think it's better to re-generate all compiled css before tagging for instance :smile:

**Comment by jimblue** [comment]
Hey @clemdesign! That's cool, thanks to resolve this 😄 !
I guess Grav Team will re-generate all compiled css.

**Comment by rhukster** [comment]
I've implemented this in 1.7 branch (with some enhancements)

**Pull request closed without merging**
