### PR TITLE
Added unset functionality to pagemedia (dropzone)

### PR DESCRIPTION
**Pull request by hdwebpros**
Unset removes the file from the page without deleting it from the system. This is mentioned in issue: https://github.com/getgrav/grav-plugin-admin/issues/1158

To test this out

- apply the code
- run `gulp` in `themes/grav`
- create or use a page that uses a blueprint that allows for multiple files
- insert 3 or so files and save
- click the "unset" button and save

The intended result is that the file is removed from the page, but not the system. This is especially important if you have files, like images, that are used on multiple pages and you want to remove them from one.

### CODE REVIEW

**Comment by hdwebpros** [comment]
Tested operational (in Chrome and Firefox)

**Comment by rhukster** [comment]
Will have @w00fz review.. thanks.

**Comment by w00fz** [comment]
Thanks @hdwebpros i left a couple of comments.

Also, am I understanding right that you have now set the `unset` with the `x` icon and the remove with the **trash bin** icon?

**Comment by hdwebpros** [comment]
That is correct. I'm open for suggestions but it seemed the most logical route

**Comment by hdwebpros** [comment]
@w00fz I'm not seeing any other comments. I'm checking from my phone so that may have something to do with that.

**Comment by w00fz** [comment]
It’s review comments , you’ll find them in the code tab. Not sure that’ll show in mobile though.

**Comment by hdwebpros** [comment]
@w00fz I don't think extra comments posted. I'm not seeing any. But please let me know if you want feedback or help with anything.

**Comment by hdwebpros** [comment]
I have updated the unset.js file with your suggested changes. I tested local and they worked.

**Comment by w00fz** [comment]
Hey @hdwebpros I just pushed a few changes because it wasn't fully working for me. Can you test it out?

I also merged this with latest admin so that it will be easier to merge the PR.

Thanks!

**Comment by rhukster** [comment]
Thanks merged into develop for 1.7.1 release

**Pull request merged**
